import { chromium } from 'playwright';
import { mkdirSync } from 'node:fs';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
await page.goto('http://localhost:5183/', { waitUntil: 'networkidle' });
await page.waitForSelector('.studio', { timeout: 15000 });
await page.locator('.rail-button[title="Script"]').click();
await page.waitForTimeout(500);
mkdirSync('.research/screenshots', { recursive: true });
await page.screenshot({ path: '.research/screenshots/script-panel.png' });
await browser.close();
console.log('screenshot saved');
